import { useState } from "react";
import { ArrowRight, BookOpen, Check, ChevronDown, CircleHelp, Code2, Compass, Languages, Lightbulb, Moon, Play, Plus, Search, Sparkles, Sun, Target, X } from "lucide-react";

const roadmap = [["01", "Computer basics", "Foundations", "12 lessons", true], ["02", "Computer science", "Logic & thinking", "14 lessons", false], ["03", "Web development", "Build for the web", "18 lessons", false], ["04", "Python programming", "Code with confidence", "16 lessons", false], ["05", "Databases", "Store knowledge", "10 lessons", false], ["06", "Software development", "Ship professionally", "15 lessons", false], ["07", "Artificial intelligence", "Build with AI", "13 lessons", false]] as const;
const vocabulary = [["Computer", "ኮምፒውተር", "A machine that processes information."], ["Hardware", "የአካል ክፍሎች", "The physical parts you can touch."], ["Software", "ሶፍትዌር", "Instructions that tell a computer what to do."]];

export default function Home() {
  const [dark, setDark] = useState(false); const [amharic, setAmharic] = useState(false); const [drawer, setDrawer] = useState(false); const [search, setSearch] = useState("");
  const labels = amharic ? { hello: "ሰላም, ሚህራት", subtitle: "የእውቀት ጉዞዎን ይቀጥሉ", start: "ትምህርቱን ጀምር", roadmap: "የትምህርት መንገድ", today: "የዛሬ ትምህርት" } : { hello: "Good morning, Mihrat", subtitle: "Continue your journey to becoming a technology builder.", start: "Start lesson", roadmap: "Your learning roadmap", today: "Today’s lesson" };
  return <div className={`app-shell ${dark ? "theme-dark" : ""}`}>
    <aside className={`sidebar ${drawer ? "open" : ""}`}><div className="brand"><div className="brand-mark">P</div><div><strong>PARADOXIT</strong><span>Learning systems</span></div><button className="close-drawer" onClick={() => setDrawer(false)}><X size={18} /></button></div><div className="profile"><div className="avatar">MA</div><div><strong>Mihrat Ashenafi</strong><span>Builder in progress</span></div><ChevronDown size={15} /></div><nav><span className="nav-label">Workspace</span><a className="active"><Compass size={17} /> Overview</a><a><BookOpen size={17} /> My lessons <b>1</b></a><a><Target size={17} /> Progress</a><span className="nav-label second">Build</span><a><Lightbulb size={17} /> LifeHelper project</a><a><Code2 size={17} /> Project lab</a></nav><div className="sidebar-bottom"><div className="mentor-card"><Sparkles size={16} /><div><strong>AI mentor ready</strong><span>Ask me anything about today’s lesson.</span></div></div><a className="settings-link"><CircleHelp size={16} /> Help & learning guide</a></div></aside>
    {drawer && <button className="scrim" onClick={() => setDrawer(false)} aria-label="Close menu" />}<main className="main-content"><header className="topbar"><button className="mobile-menu" onClick={() => setDrawer(true)}><span /><span /></button><div className="breadcrumbs"><span>Workspace</span><ArrowRight size={13} /><strong>Overview</strong></div><div className="top-actions"><div className="search"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search lessons, topics..." /></div><button className="icon-button" onClick={() => setAmharic(!amharic)} title="Change language"><Languages size={18} /><span>{amharic ? "አማ" : "EN"}</span></button><button className="icon-button" onClick={() => setDark(!dark)} title="Toggle theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="notification">3</button><div className="mini-avatar">MA</div></div></header>
    <div className="page-wrap"><section className="hero"><div className="hero-copy"><p className="eyebrow">PERSONAL LEARNING SYSTEM <span /> DAY 01</p><h1>{labels.hello}.<br /><em>Let’s build something real.</em></h1><p className="hero-subtitle">{labels.subtitle}</p><div className="hero-actions"><button className="primary-button"><Play size={15} fill="currentColor" /> {labels.start} <ArrowRight size={15} /></button><button className="text-button">View learning plan <ArrowRight size={15} /></button></div></div><div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><span>01</span><small>DAY</small></div><div className="orbit-tag tag-top">CURIOUS<br /><b>→</b></div><div className="orbit-tag tag-bottom">CONSISTENT<br /><b>→</b></div></div></section>
    <section className="stats-row"><div><span>Current phase</span><strong>01 <small>/ 12</small></strong><p>Computer basics</p></div><div><span>Learning streak</span><strong>01 <small>day</small></strong><p className="green">Keep it going <span>↗</span></p></div><div><span>Overall progress</span><strong>02<small>%</small></strong><div className="progress"><i style={{ width: "2%" }} /></div></div><div><span>Next milestone</span><strong>First project</strong><p>Portfolio website</p></div></section>
    <div className="content-grid"><section className="lesson-card"><div className="section-head"><div><p className="eyebrow">{labels.today}</p><h2>What is a computer?</h2></div><span className="lesson-number">01 / 15</span></div><div className="lesson-body"><div className="lesson-icon"><span>✦</span></div><div className="lesson-text"><p>A computer is an electronic machine that receives information, processes it, stores it, and produces a result.</p><p className="amharic">ኮምፒውተር መረጃን የሚቀበል፣ የሚያስተካክል፣ የሚያስቀምጥ እና ውጤት የሚያሳይ የኤሌክትሮኒክ ማሽን ነው።</p><div className="lesson-meta"><span><BookOpen size={14} /> 15 min lesson</span><span><Check size={14} /> Beginner friendly</span></div></div></div><div className="lesson-footer"><span>Next: Hardware & software</span><button className="outline-button">Open lesson <ArrowRight size={15} /></button></div></section><aside className="daily-card"><div className="daily-head"><span className="eyebrow">YOUR DAILY SYSTEM</span><Sparkles size={16} /></div><h3>Learn slowly.<br /><em>Build deeply.</em></h3><p>One topic at a time, explained in English and Amharic. No shortcuts. No assumptions.</p><div className="system-list"><span><i>01</i> Learn the concept</span><span><i>02</i> Practice with an example</span><span><i>03</i> Answer your mentor</span></div></aside></div>
    <section className="lower-grid"><div className="roadmap-card"><div className="section-head"><div><p className="eyebrow">THE LONG VIEW</p><h2>{labels.roadmap}</h2></div><button className="text-button">See all phases <ArrowRight size={15} /></button></div><div className="roadmap-list">{roadmap.map(([num, title, desc, lessons, done]) => <div className={`roadmap-item ${done ? "done" : ""}`} key={num}><span className="roadmap-num">{num}</span><div><strong>{title}</strong><p>{desc} · {lessons}</p></div><span className="phase-status">{done ? <Check size={14} /> : "—"}</span></div>)}</div></div><div className="vocab-card"><div className="section-head"><div><p className="eyebrow">ENGLISH × AMHARIC</p><h2>Today’s vocabulary</h2></div><Languages size={18} /></div>{vocabulary.map(([word, am, desc]) => <div className="vocab-row" key={word}><div className="word-letter">{word[0]}</div><div><strong>{word} <span>· {am}</span></strong><p>{desc}</p></div></div>)}<button className="outline-button full">Open vocabulary <ArrowRight size={15} /></button></div></section>
    <section className="lifehelper"><div className="lifehelper-mark"><Plus size={22} /></div><div><p className="eyebrow">YOUR NORTH STAR PROJECT</p><h2>LifeHelper</h2><p>A technology platform for solving everyday human problems — one thoughtful experiment at a time.</p></div><button className="dark-button">Explore project plan <ArrowRight size={15} /></button></section><footer><span>© 2026 Paradoxit Learning Systems</span><span>Built for a better tomorrow · <strong>በትጋት ተማር</strong></span></footer></div></main></div>;
}
